services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: echo-bridge-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    networks:
      - echo-bridge-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - backend-logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: echo-bridge-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - echo-bridge-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  echo-bridge-network:
    driver: bridge
    name: echo-bridge-network

volumes:
  backend-logs:
    driver: local 